TARGET = controller
TEMPLATE = lib
CONFIG += shared c++11 x86_64
QT += network sql xml
QT -= gui
greaterThan(QT_MAJOR_VERSION, 4): QT += qml
DEFINES += TF_DLL
DESTDIR = ../lib
INCLUDEPATH += ../helpers ../models ${CAFFE_ROOT}/build/include ${CAFFE_ROOT}/include /usr/local/cuda/include
DEPENDPATH  += ../helpers ../models
LIBS += -L../lib -lhelper -lmodel -Wl,-rpath,${CAFFE_ROOT}/build/lib -L${CAFFE_ROOT}/build/lib -lcaffe -lglog
macx {
  DEFINES += USE_ACCELERATE CPU_ONLY
  HOMEBREW_PREFIX = $$system(brew --prefix)
  ACCELERATE_FRAMEWORK = /System/Library/Frameworks/Accelerate.framework
  VECLIB_FRAMEWORK = $${ACCELERATE_FRAMEWORK}/Versions/Current/Frameworks/vecLib.framework
  INCLUDEPATH += $${HOMEBREW_PREFIX}/include $${VECLIB_FRAMEWORK}/Versions/Current/Headers
  LIBS += -framework Accelerate -L$${HOMEBREW_PREFIX}/lib -lboost_system
}
MOC_DIR = .obj/
OBJECTS_DIR = .obj/

include(../appbase.pri)

HEADERS += applicationcontroller.h
SOURCES += applicationcontroller.cpp
HEADERS += maincontroller.h
SOURCES += maincontroller.cpp
HEADERS += applicationendpoint.h
SOURCES += applicationendpoint.cpp
HEADERS += logtailendpoint.h
SOURCES += logtailendpoint.cpp
HEADERS += solverprotocontroller.h
SOURCES += solverprotocontroller.cpp
HEADERS += caffecontextcontroller.h
SOURCES += caffecontextcontroller.cpp
HEADERS += workspacecontroller.h
SOURCES += workspacecontroller.cpp
HEADERS += neuralnetworkcontroller.h
SOURCES += neuralnetworkcontroller.cpp
HEADERS += caffetrainedmodelcontroller.h
SOURCES += caffetrainedmodelcontroller.cpp
HEADERS += classlabelcontroller.h
SOURCES += classlabelcontroller.cpp
HEADERS += traindatasetcontroller.h
SOURCES += traindatasetcontroller.cpp
HEADERS += indexcontroller.h
SOURCES += indexcontroller.cpp
HEADERS += traincontroller.h
SOURCES += traincontroller.cpp
HEADERS += tagcontroller.h
SOURCES += tagcontroller.cpp
HEADERS += datasetmakercontroller.h
SOURCES += datasetmakercontroller.cpp
#HEADERS += statuscontroller.h
#SOURCES += statuscontroller.cpp
#HEADERS += caffedatacontroller.h
#SOURCES += caffedatacontroller.cpp
HEADERS += datasetcontroller.h
SOURCES += datasetcontroller.cpp
